spring:
  application:
    name: hello
  profiles:
    active: local

tanzu:
  env: default

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
